services:
  dw:
    image: postgres:16-alpine
    container_name: ecci_dw
    environment:
      POSTGRES_DB: ecci_dw
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
    ports:
      - "5432:5432"
    volumes:
      - dw_data:/var/lib/postgresql/data
      - ./sql/ddl:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etl_user -d ecci_dw"]
      interval: 10s
      timeout: 5s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    container_name: ecci_metabase
    ports:
      - "3000:3000"
    depends_on:
      dw:
        condition: service_healthy

volumes:
  dw_data: